/*
 * Movie Rating Service
 * This is a movie rating service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.MovieModelGet;
import io.swagger.client.model.MovieModelPut;
import io.swagger.client.model.ResponseMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MovieInformationApi
 */
@Ignore
public class MovieInformationApiTest {

    private final MovieInformationApi api = new MovieInformationApi();

    
    /**
     * information about a movie
     *
     * Details of a movie
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMovieTest() throws ApiException {
        MovieModelPut body = null;
        ResponseMessage response = api.createMovie(body);

        // TODO: test validations
    }
    
    /**
     * information about a movie.
     *
     * Details of a movie
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void outputMovieTest() throws ApiException {
        MovieModelGet response = api.outputMovie();

        // TODO: test validations
    }
    
}
