/*
 * Movie Rating Service
 * This is a movie rating service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseMessage;
import io.swagger.client.model.UserModelGet;
import io.swagger.client.model.UserModelPut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserInformationApi
 */
@Ignore
public class UserInformationApiTest {

    private final UserInformationApi api = new UserInformationApi();

    
    /**
     * user information
     *
     * Information regarding a particular user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        UserModelPut body = null;
        ResponseMessage response = api.createUser(body);

        // TODO: test validations
    }
    
    /**
     * user information
     *
     * information of all the users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void outputUserTest() throws ApiException {
        UserModelGet response = api.outputUser();

        // TODO: test validations
    }
    
}
