/*
 * Movie Rating Service
 * This is a movie rating service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MovieModelPut
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-03T12:08:41.006+05:30")
public class MovieModelPut {
  @SerializedName("movieName")
  private String movieName = null;

  @SerializedName("actor")
  private String actor = null;

  @SerializedName("actress")
  private String actress = null;

  @SerializedName("year")
  private Integer year = null;

  public MovieModelPut movieName(String movieName) {
    this.movieName = movieName;
    return this;
  }

   /**
   * Get movieName
   * @return movieName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMovieName() {
    return movieName;
  }

  public void setMovieName(String movieName) {
    this.movieName = movieName;
  }

  public MovieModelPut actor(String actor) {
    this.actor = actor;
    return this;
  }

   /**
   * Get actor
   * @return actor
  **/
  @ApiModelProperty(required = true, value = "")
  public String getActor() {
    return actor;
  }

  public void setActor(String actor) {
    this.actor = actor;
  }

  public MovieModelPut actress(String actress) {
    this.actress = actress;
    return this;
  }

   /**
   * Get actress
   * @return actress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getActress() {
    return actress;
  }

  public void setActress(String actress) {
    this.actress = actress;
  }

  public MovieModelPut year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @ApiModelProperty(value = "")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieModelPut movieModelPut = (MovieModelPut) o;
    return Objects.equals(this.movieName, movieModelPut.movieName) &&
        Objects.equals(this.actor, movieModelPut.actor) &&
        Objects.equals(this.actress, movieModelPut.actress) &&
        Objects.equals(this.year, movieModelPut.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movieName, actor, actress, year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieModelPut {\n");
    
    sb.append("    movieName: ").append(toIndentedString(movieName)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    actress: ").append(toIndentedString(actress)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

